
server:
  port: 8080

spring:
  datasource:
    url: ${DEV_DB_URL:jdbc:mysql://localhost:3306/oao}
    username: ${DEV_DB_USERNAME:root}
    password: ${DEV_DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update        # 공통은 안전하게 none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

ai:
   openai:
     url: https://api.openai.com/v1/images/generations
     api-key: ${OPENAI_API_KEY}

cloud:
  aws:
    credentials:
      access-key: YOUR_AWS_ACCESS_KEY # 이 부분에 실제 키를 입력했는지 확인
      secret-key: YOUR_AWS_SECRET_KEY # 이 부분에 실제 키를 입력했는지 확인
    region:
      static: ap-northeast-2 # 사용 중인 리전 확인
    s3:
      bucket: YOUR_S3_BUCKET_NAME # 버킷 이름 확인